version: '3'

services:
  nginx:
    container_name: vcf-offline-depot-nginx
    image: nginxinc/nginx-unprivileged:latest
    volumes:
     - ${PWD}/.htpasswd:/etc/nginx/.htpasswd:ro
     - ${PWD}/default.conf:/etc/nginx/conf.d/default.conf:ro
     - ${PWD}/ssl.conf:/etc/nginx/ssl.conf:ro
     - ${PWD}/nginx.pem:/etc/nginx/ssl/nginx.pem:ro
     - ${PWD}/nginx.key:/etc/nginx/ssl/nginx.key:ro
     - /srv/www:/usr/share/nginx/html:ro
    ports:
     - '80:80'
     - '443:443'
