version: '3'

services:
  nginx:
    container_name: vcf-offline-depot-nginx
    image: nginxinc/nginx-unprivileged:latest
    volumes:
     - ${PWD}/.htpasswd:/etc/nginx/.htpasswd:ro
     - ${PWD}/default.conf:/etc/nginx/templates/default.conf.template:ro
     - ${PWD}/ssl.conf:/etc/nginx/ssl.conf:ro
     - ${PWD}/nginx.pem:/etc/nginx/ssl/nginx.pem:ro
     - ${PWD}/nginx.key:/etc/nginx/ssl/nginx.key:ro
     - /srv/www:/usr/share/nginx/html:ro
    ports:
     - "${HTTP_PORT}:${HTTP_PORT}"
     - "${HTTPS_PORT}:${HTTPS_PORT}"
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
