---
- name: Create private key, certificate signing request, and optionally a self-signed certificate
  become: false
  hosts: localhost
  gather_facts: false
  vars:
    webserver_config_path: '/srv/vcf-offline-depot-nginx'
    certificate_path: '{{ webserver_config_path }}/nginx.pem'
    csr_path: '{{ webserver_config_path }}/nginx.csr'
    privatekey_path: '{{ webserver_config_path }}/nginx.key'
    privatekey_size: 4096
    privatekey_type: 'RSA'
    common_name: 'depot.graa.dev'
    country_name: 'NO'
    organization_name: 'graa.dev'
    organizational_unit_name: 'graa.dev'
    subject_alt_name:
      - 'DNS:{{ common_name }}'
  tasks:
   - name: Create private key, certificate signing request, and optionally a self-signed certificate
     block:
      - name: Generate an OpenSSL private key
        community.crypto.openssl_privatekey:
          path: '{{ privatekey_path }}'
          size: '{{ privatekey_size }}'
          type: '{{ privatekey_type }}'
        tags:
        - privateKey

      - name: Set permissions on private key
        ansible.builtin.file:
          path: '{{ privatekey_path }}'
          state: file
          mode: '0640'
        tags:
        - privateKey

      - name: Generate an OpenSSL Certificate Signing Request
        community.crypto.openssl_csr:
          path: '{{ csr_path }}'
          privatekey_path: '{{ privatekey_path }}'
          common_name: '{{ common_name }}'
          country_name: '{{ country_name }}'
          organization_name: '{{ organization_name }}'
          organizational_unit_name: '{{ organizational_unit_name }}'
          subject_alt_name: '{{ subject_alt_name }}'
          extended_key_usage: '1.3.6.1.5.5.7.3.1'
          use_common_name_for_san: true
        register: result
        tags:
        - csr

      - name: Create self-signed certificate from CSR
        community.crypto.x509_certificate:
          path: '{{ certificate_path }}'
          csr_path: '{{ csr_path }}'
          privatekey_path: '{{ privatekey_path }}'
          provider: selfsigned
        tags:
        - selfSigned
